export default function mapCity(city) {
    const tier1Cities = [
        "Ahmedabad",
        "Bangalore",
        "Chennai",
        "Delhi",
        "Hyderabad",
        "Kolkata",
        "Mumbai",
        "Pune",
    ];
    const tier2Cities = [
        "Agra",
        "Ajmer",
        "Aligarh",
        "Amravati",
        "Amritsar",
        "Asansol",
        "Aurangabad",
        "Bareilly",
        "Belgaum",
        "Bhavnagar",
        "Bhiwandi",
        "Bhopal",
        "Bhubaneswar",
        "Bikaner",
        "Bilaspur",
        "Bokaro Steel City",
        "Chandigarh",
        "Coimbatore",
        "Cuttack",
        "Dehradun",
        "Dhanbad",
        "Bhilai",
        "Durgapur",
        "Dindigul",
        "Erode",
        "Faridabad",
        "Firozabad",
        "Ghaziabad",
        "Gorakhpur",
        "Gulbarga",
        "Guntur",
        "Gwalior",
        "Gurgaon",
        "Guwahati",
        "Hamirpur",
        "Hubli–Dharwad",
        "Indore",
        "Jabalpur",
        "Jaipur",
        "Jalandhar",
        "Jammu",
        "Jamnagar",
        "Jamshedpur",
        "Jhansi",
        "Jodhpur",
        "Kakinada",
        "Kannur",
        "Kanpur",
        "Karnal",
        "Kochi",
        "Kolhapur",
        "Kollam",
        "Kozhikode",
        "Kurnool",
        "Ludhiana",
        "Lucknow",
        "Madurai",
        "Malappuram",
        "Mathura",
        "Mangalore",
        "Meerut",
        "Moradabad",
        "Mysore",
        "Nagpur",
        "Nanded",
        "Nashik",
        "Nellore",
        "Noida",
        "Patna",
        "Pondicherry",
        "Purulia",
        "Prayagraj",
        "Raipur",
        "Rajkot",
        "Rajahmundry",
        "Ranchi",
        "Rourkela",
        "Ratlam",
        "Salem",
        "Sangli",
        "Shimla",
        "Siliguri",
        "Solapur",
        "Srinagar",
        "Surat",
        "Thanjavur",
        "Thiruvananthapuram",
        "Thrissur",
        "Tiruchirappalli",
        "Tirunelveli",
        "Tiruvannamalai",
        "Ujjain",
        "Bijapur",
        "Vadodara",
        "Varanasi",
        "Vasai-Virar City",
        "Vijayawada",
        "Visakhapatnam",
        "Vellore",
        "Warangal",
    ];

    if (tier1Cities.includes(city)) {
        return 1;
    } else if (tier2Cities.includes(city)) {
        return 2;
    } else {
        return 3;
    }
}
