
GET http://127.0.0.1:5000/ HTTP/1.1



###

POST http://127.0.0.1:5000/predict_property HTTP/1.1
content-type: application/json

{
    "posted_by": 0,
    "under_construction": 0,
    "rera": 0,
    "bhk": 2,
    "square_feet": 3000,
    "ready_to_move": 0,
    "resale": 0,
    "city": "Bangalore",
    "locality": "Whitefield"
}

###
POST http://127.0.0.1:5000/predict_loan HTTP/1.1
content-type: application/json

{
    "loan_amnt": 50000,
        "debt_settlement_flag": 0,
        "int_rate": 7,
        "annual_income": 1000000,
        "installment": 10000,
        "funded_amnt_inv": 0,
        "dti": 0,
        "tot_coll_amnt": 0,
        "mths_since_recent_bc": 24,
        "revol_bal": 0,
        "out_prncp": 0,
        "mths_since_rcnt_il": 0,
        "collection_recovery_fee": 0,
        "il_util": 0
}